// <auto-generated />
using EmployeeManagement_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement_Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230918072027_AddPhotoPathClumn")]
    partial class AddPhotoPathClumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement_Demo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 5,
                            Email = "mary@egtech.com",
                            Name = "Mary",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "mark@egtech.com",
                            Name = "Mark",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 3,
                            Department = 3,
                            Email = "kareem@egtech.com",
                            Name = "Kareem",
                            PhotoPath = ""
                        },
                        new
                        {
                            Id = 4,
                            Department = 4,
                            Email = "fady@egtech.com",
                            Name = "Fady",
                            PhotoPath = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
